version: '3.10'

services:
  app:
    container_name: 'fastapi-for-students-app'
    build: 
      context: .
      dockerfile: Dockerfile 
    command: bash -c "alembic upgrade head && gunicorn -w 4 -k uvicorn.workers.UvicornWorker src.main:app -b 0.0.0.0:8000"

    ports:
      - "80:8000" 

    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWD}@database:5432/${DB_NAME}

    depends_on:
      - database

  database:
    image: postgres:latest
    expose:
      - 5432

    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWD}
      POSTGRES_DB: ${DB_NAME}

    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
