"""Init

Revision ID: 2920d23a7314
Revises: b3e92f2ae155
Create Date: 2022-10-30 12:38:03.806264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2920d23a7314'
down_revision = 'b3e92f2ae155'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_acounts_id', table_name='acounts')
    op.drop_table('acounts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acounts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('owner_acc_id', sa.INTEGER(), nullable=True),
    sa.Column('owner_dep_id', sa.INTEGER(), nullable=True),
    sa.Column('amount', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['owner_acc_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_dep_id'], ['deposits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_acounts_id', 'acounts', ['id'], unique=False)
    # ### end Alembic commands ###
