"""Init

Revision ID: cd4b272c9697
Revises: 
Create Date: 2023-01-20 11:17:56.757778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd4b272c9697'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deposits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deposit_name', sa.String(), nullable=True),
    sa.Column('shelf_life', sa.Integer(), nullable=True),
    sa.Column('bet', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deposits_deposit_name'), 'deposits', ['deposit_name'], unique=True)
    op.create_index(op.f('ix_deposits_id'), 'deposits', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('passport', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_address'), 'users', ['address'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_passport'), 'users', ['passport'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_user_name'), 'users', ['user_name'], unique=False)
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_acc_id', sa.Integer(), nullable=True),
    sa.Column('owner_dep_id', sa.Integer(), nullable=True),
    sa.Column('date_open', sa.Date(), nullable=True),
    sa.Column('date_close', sa.Date(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_acc_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_dep_id'], ['deposits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_users_user_name'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_passport'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_address'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_deposits_id'), table_name='deposits')
    op.drop_index(op.f('ix_deposits_deposit_name'), table_name='deposits')
    op.drop_table('deposits')
    # ### end Alembic commands ###
