name: prog_circl

on: 
  push:
    branches: [master]

jobs:
  test:
    name: Test code
    runs-on: ubuntu-latest
    steps:
      - name: Get code fron repo
        uses: actions/checkout@v3
      - name: Set-up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest
        env:
          DATABASE_URL: sqlite:///./sqlite.db
  
  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Get code from repo
        uses: actions/checkout@v3
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          cat >>~/.ssh/config <<END
          Host yandex_server
            HostName ${{ secrets.HOST }}
            User ${{ secrets.LOGIN }}
            IdentityFile ~/.ssh/id_rsa
            StrictHostKeyChecking no
          END
      - name: Create .env file
        run: |
          cat >>.end <<END
          DB_USER=${{ secrets.DB_USER }}
          DB_PASSWD=${{ secrets.DB_PASSWD }}
          DB_NAME=${{ secrets.DB_NAME }}
          END
      - name: Rsync files to server
        run: rsync -rav * yandex_server:~/project
      - name: Rsync files to server
        run: rsync -rav .env yandex_server:~/project/.env
      - name: Stop containers
        run: ssh yandex_server 'sudo docker-compose -f project/docker-compose.yml down'
      - name: Build containers
        run: ssh yandex_server 'sudo docker-compose -f project/docker-compose.yml build'
      - name: Run containers
        run: ssh yandex_server 'sudo docker-compose -f project/docker-compose.yml up -d'
